import * as vscode from "vscode";

type Language = "de" | "en";

const translations = {
  de: {
    actionInitialize: "Initialisieren",
    actionRefresh: "Aktualisieren",
    actionTrackPath: "Pfad tracken",
    actionTrackCurrentFile: "Aktuelle Datei tracken",
    actionAddNote: "Neue Notiz",
    actionAddSavedCommand: "Befehl hinzufuegen",
    actionRecreateData: "Daten neu erstellen",
    actionConfigureControls: "Service bearbeiten",
    actionStart: "Starten",
    actionStop: "Stoppen",
    actionRestart: "Neustarten",
    actionStatus: "Status",
    actionAddExtraCommand: "Zusatzbefehl hinzufuegen",
    actionRemoveExtraCommand: "Zusatzbefehl entfernen",
    actionsSection: "Aktionen",
    savedCommandsSection: "Befehle",
    savedCommandRunsSection: "Letzte Ausgaben",
    workList: "Arbeitsliste",
    rawLog: "Rohlog",
    noTrackedFiles: "Keine Dateien getrackt",
    noRawLog: "Kein Rohlog",
    noSavedCommands: "Keine gespeicherten Befehle",
    noSavedCommandRuns: "Keine letzten Ausgaben",
    notInitialized: "Noch nicht initialisiert",
    initializeHint: "Aktionen > Initialisieren",
    errorLoading: "Fehler beim Laden",
    displayName: "Klarname",
    path: "Pfad",
    lastChanged: "Letzte Aenderung",
    comment: "Kommentar",
    service: "Service",
    controlStart: "Start",
    controlStop: "Stop",
    controlRestart: "Restart",
    controlStatus: "Status",
    extraCommands: "Zusatzbefehle",
    fileMissing: "Status: Datei nicht gefunden",
    changes: "Aenderungen",
    notesFile: "NOTIZEN.md",
    systemStatusFile: "SYSTEMSTATUS.md",
    hostname: "Hostname",
    osName: "OS-Name",
    osVersion: "OS-Version",
    kernel: "Kernel",
    architecture: "Architektur",
    mainIp: "Haupt-IP",
    lastRefresh: "Letzter Refresh",
    warningNotInitialized: "SSH Workspace ist noch nicht initialisiert.",
    warningInitializeFirst: "Bitte zuerst SSH Workspace initialisieren.",
    initialized: "SSH Workspace wurde initialisiert: {path}",
    refreshed: "SSH Workspace wurde aktualisiert.",
    recreateQuestion:
      "workspace-data.json neu erstellen? Arbeitsliste und Rohlog werden geloescht. SYSTEMSTATUS.md und NOTIZEN.md bleiben erhalten.",
    recreateConfirm: "Neu erstellen",
    recreated: "workspace-data.json wurde neu erstellt.",
    addNotePrompt: "Titel fuer die neue Notizdatei",
    addNotePlaceholder: "z. B. Befehle Apache oder Deployment April",
    emptyNote: "Titel ist leer.",
    noteAdded: "Notizdatei erstellt: {title}.",
    noteDeleted: "Notizdatei geloescht: {title}.",
    noNoteSelected: "Keine Notiz ausgewaehlt.",
    deleteNote: "Notiz loeschen",
    deleteNoteQuestion: "Notizdatei wirklich loeschen: {title}?",
    deleteNoteConfirm: "Loeschen",
    deleteGeneralNoteBlocked: "NOTIZEN.md bleibt als allgemeine Notizdatei erhalten.",
    savedCommandNamePrompt: "Klarname fuer den Befehl",
    savedCommandNameRequired: "Klarname ist erforderlich.",
    savedCommandCommandPrompt: "Shell-Befehl",
    savedCommandCommandRequired: "Befehl ist erforderlich.",
    savedCommandNotePrompt: "Notiz zum Befehl (optional)",
    savedCommandAdded: "Befehl hinzugefuegt.",
    savedCommandUpdated: "Befehl aktualisiert.",
    savedCommandDuplicated: "Befehl dupliziert.",
    savedCommandDeleted: "Befehl geloescht: {name}.",
    savedCommandNotFound: "Befehl nicht gefunden.",
    savedCommandRunSuccess: "Befehl erfolgreich ausgefuehrt: {name}.",
    savedCommandRunFailed: "Befehl mit Fehler beendet: {name}.",
    editSavedCommand: "Befehl bearbeiten",
    duplicateSavedCommand: "Befehl duplizieren",
    deleteSavedCommand: "Befehl loeschen",
    deleteSavedCommandQuestion: "Befehl wirklich loeschen: {name}?",
    deleteSavedCommandConfirm: "Loeschen",
    runSuccess: "Erfolg",
    runFailed: "Fehler",
    commandLabel: "Befehl",
    startedAt: "Start",
    finishedAt: "Ende",
    exitCode: "Exit-Code",
    outputLabel: "Output",
    noOutput: "Kein Output",
    noFileSelected: "Keine Datei ausgewaehlt.",
    noPathSelected: "Kein Pfad ausgewaehlt.",
    fileNoLongerExists: "Datei existiert nicht mehr: {path}",
    noEditorFile: "Keine lokale Remote-Datei im aktiven Editor.",
    internalFileNotTracked: "Interne SSH Workspace-Dateien werden nicht in der Arbeitsliste getrackt.",
    fileTracked: "Datei wird getrackt: {path}",
    trackPathPrompt: "Absoluter Pfad auf dem verbundenen Remote-Host",
    pathRequired: "Pfad ist erforderlich.",
    absolutePathRequired: "Bitte einen absoluten Pfad angeben.",
    pathRecordedMissing: "Pfad wurde aufgenommen, Datei existiert aber nicht: {path}",
    pathTracked: "Pfad wird getrackt: {path}",
    fileNotTracked: "Datei ist noch nicht getrackt.",
    editComment: "Kommentar bearbeiten",
    editDisplayName: "Klarname bearbeiten",
    editControlCommands: "Service bearbeiten",
    controlCommandsSaved: "Service gespeichert. Standardaktionen werden automatisch daraus erzeugt.",
    serviceNamePrompt: "Systemd-Service fuer diese Datei. Starten, Stoppen, Neustarten und Status werden automatisch daraus erzeugt.",
    serviceNamePlaceholder: "z. B. nginx.service; leer lassen zum Entfernen",
    controlCommandPrompt: "{action}-Befehl fuer diese Datei",
    controlCommandPlaceholder: "leer lassen, um bei Service-Eintrag automatisch systemctl zu nutzen",
    controlCommandMissing: "Kein {action}-Befehl fuer diese Datei hinterlegt.",
    runningControlCommand: "{action} wird im Terminal ausgefuehrt.",
    extraCommandLabelPrompt: "Anzeigename fuer den Zusatzbefehl",
    extraCommandCommandPrompt: "Shell-Befehl fuer den Zusatzbefehl",
    extraCommandAdded: "Zusatzbefehl hinzugefuegt.",
    extraCommandRemoved: "Zusatzbefehl entfernt.",
    extraCommandNotFound: "Zusatzbefehl nicht gefunden.",
    extraCommandLabelRequired: "Anzeigename ist erforderlich.",
    extraCommandCommandRequired: "Befehl ist erforderlich.",
    pathCopied: "Pfad kopiert.",
    metadataUpdated: "Metadaten aktualisiert.",
    open: "Oeffnen"
  },
  en: {
    actionInitialize: "Initialize",
    actionRefresh: "Refresh",
    actionTrackPath: "Track Path",
    actionTrackCurrentFile: "Track Current File",
    actionAddNote: "New Note",
    actionAddSavedCommand: "Add Command",
    actionRecreateData: "Recreate Data",
    actionConfigureControls: "Edit Service",
    actionStart: "Start",
    actionStop: "Stop",
    actionRestart: "Restart",
    actionStatus: "Status",
    actionAddExtraCommand: "Add Extra Command",
    actionRemoveExtraCommand: "Remove Extra Command",
    actionsSection: "Actions",
    savedCommandsSection: "Commands",
    savedCommandRunsSection: "Recent Output",
    workList: "Work List",
    rawLog: "Raw Log",
    noTrackedFiles: "No tracked files",
    noRawLog: "No raw log",
    noSavedCommands: "No saved commands",
    noSavedCommandRuns: "No recent output",
    notInitialized: "Not initialized yet",
    initializeHint: "Actions > Initialize",
    errorLoading: "Error while loading",
    displayName: "Display name",
    path: "Path",
    lastChanged: "Last change",
    comment: "Comment",
    service: "Service",
    controlStart: "Start",
    controlStop: "Stop",
    controlRestart: "Restart",
    controlStatus: "Status",
    extraCommands: "Extra commands",
    fileMissing: "Status: file not found",
    changes: "changes",
    notesFile: "NOTIZEN.md",
    systemStatusFile: "SYSTEMSTATUS.md",
    hostname: "Hostname",
    osName: "OS name",
    osVersion: "OS version",
    kernel: "Kernel",
    architecture: "Architecture",
    mainIp: "Main IP",
    lastRefresh: "Last refresh",
    warningNotInitialized: "SSH Workspace is not initialized yet.",
    warningInitializeFirst: "Please initialize SSH Workspace first.",
    initialized: "SSH Workspace initialized: {path}",
    refreshed: "SSH Workspace refreshed.",
    recreateQuestion:
      "Recreate workspace-data.json? Work list and raw log will be deleted. SYSTEMSTATUS.md and NOTIZEN.md will be kept.",
    recreateConfirm: "Recreate",
    recreated: "workspace-data.json was recreated.",
    addNotePrompt: "Title for the new note file",
    addNotePlaceholder: "e.g. Apache Commands or Deployment April",
    emptyNote: "Title is empty.",
    noteAdded: "Note file created: {title}.",
    noteDeleted: "Note file deleted: {title}.",
    noNoteSelected: "No note selected.",
    deleteNote: "Delete Note",
    deleteNoteQuestion: "Delete note file: {title}?",
    deleteNoteConfirm: "Delete",
    deleteGeneralNoteBlocked: "NOTIZEN.md remains the general notes file.",
    savedCommandNamePrompt: "Display name for the command",
    savedCommandNameRequired: "Display name is required.",
    savedCommandCommandPrompt: "Shell command",
    savedCommandCommandRequired: "Command is required.",
    savedCommandNotePrompt: "Note for the command (optional)",
    savedCommandAdded: "Command added.",
    savedCommandUpdated: "Command updated.",
    savedCommandDuplicated: "Command duplicated.",
    savedCommandDeleted: "Command deleted: {name}.",
    savedCommandNotFound: "Command not found.",
    savedCommandRunSuccess: "Command completed successfully: {name}.",
    savedCommandRunFailed: "Command failed: {name}.",
    editSavedCommand: "Edit Command",
    duplicateSavedCommand: "Duplicate Command",
    deleteSavedCommand: "Delete Command",
    deleteSavedCommandQuestion: "Delete command: {name}?",
    deleteSavedCommandConfirm: "Delete",
    runSuccess: "Success",
    runFailed: "Failed",
    commandLabel: "Command",
    startedAt: "Started",
    finishedAt: "Finished",
    exitCode: "Exit code",
    outputLabel: "Output",
    noOutput: "No output",
    noFileSelected: "No file selected.",
    noPathSelected: "No path selected.",
    fileNoLongerExists: "File no longer exists: {path}",
    noEditorFile: "No local remote file in the active editor.",
    internalFileNotTracked: "Internal SSH Workspace files are not tracked in the work list.",
    fileTracked: "File is tracked: {path}",
    trackPathPrompt: "Absolute path on the connected remote host",
    pathRequired: "Path is required.",
    absolutePathRequired: "Please enter an absolute path.",
    pathRecordedMissing: "Path was recorded, but the file does not exist: {path}",
    pathTracked: "Path is tracked: {path}",
    fileNotTracked: "File is not tracked yet.",
    editComment: "Edit Comment",
    editDisplayName: "Edit Display Name",
    editControlCommands: "Edit Service",
    controlCommandsSaved: "Service saved. Default actions are generated automatically from it.",
    serviceNamePrompt: "Systemd service for this file. Start, stop, restart, and status are generated automatically from it.",
    serviceNamePlaceholder: "e.g. nginx.service; leave empty to remove it",
    controlCommandPrompt: "{action} command for this file",
    controlCommandPlaceholder: "leave empty to auto-use systemctl when a service is set",
    controlCommandMissing: "No {action} command is configured for this file.",
    runningControlCommand: "{action} is being executed in the terminal.",
    extraCommandLabelPrompt: "Display label for the extra command",
    extraCommandCommandPrompt: "Shell command for the extra command",
    extraCommandAdded: "Extra command added.",
    extraCommandRemoved: "Extra command removed.",
    extraCommandNotFound: "Extra command not found.",
    extraCommandLabelRequired: "Label is required.",
    extraCommandCommandRequired: "Command is required.",
    pathCopied: "Path copied.",
    metadataUpdated: "Metadata updated.",
    open: "Open"
  }
} as const;

type TranslationKey = keyof typeof translations.de;

export function getLanguage(): Language {
  const configured = vscode.workspace.getConfiguration("sshWorkspace").get<string>("language", "de");
  return configured === "en" ? "en" : "de";
}

export function t(key: TranslationKey, values: Record<string, string> = {}): string {
  let text: string = translations[getLanguage()][key] ?? translations.de[key];

  for (const [name, value] of Object.entries(values)) {
    text = text.split(`{${name}}`).join(value);
  }

  return text;
}
